import type { SportDefinition } from '../core/types'

export const basketballDefinition: SportDefinition = {
  slug: 'basketball',
  name: 'Basketball',
  leagueTypes: ['school', 'club', 'recreational', 'tournament'],
  positions: ['PG', 'SG', 'SF', 'PF', 'C'],
  periods: { type: 'quarters', count: 4 },
  score: { unit: 'points', highScoreWins: true },
  theme: { accent: { light: '249 115 22', dark: '251 146 60' } },
  events: {
    FT_MADE: { label: 'Free throw made', shortLabel: '+1 FT', group: 'Scoring', points: 1, requiresPlayer: true, requiresTeam: true, quickAdjust: true, statDeltas: { points: 1, ftMade: 1, ftAttempted: 1 }, flow: { suggestsEvents: ['ASSIST'], flipsPossession: true } },
    FT_MISS: { label: 'Free throw missed', shortLabel: 'MISS FT', group: 'Misses', requiresPlayer: true, requiresTeam: true, statDeltas: { ftAttempted: 1 }, flow: { suggestsEvents: ['REBOUND_OFF', 'REBOUND_DEF'], keepsPlayer: false } },
    FG2_MADE: { label: 'Two made', shortLabel: '+2 FG', group: 'Scoring', points: 2, requiresPlayer: true, requiresTeam: true, quickAdjust: true, statDeltas: { points: 2, fgMade: 1, fgAttempted: 1 }, flow: { suggestsEvents: ['ASSIST'], flipsPossession: true } },
    FG2_MISS: { label: 'Two missed', shortLabel: 'MISS 2', group: 'Misses', requiresPlayer: true, requiresTeam: true, statDeltas: { fgAttempted: 1 }, flow: { suggestsEvents: ['REBOUND_OFF', 'REBOUND_DEF'], keepsPlayer: false } },
    FG3_MADE: { label: 'Three made', shortLabel: '+3 3PT', group: 'Scoring', points: 3, requiresPlayer: true, requiresTeam: true, quickAdjust: true, statDeltas: { points: 3, fgMade: 1, fgAttempted: 1, threeMade: 1, threeAttempted: 1 }, flow: { suggestsEvents: ['ASSIST'], flipsPossession: true } },
    FG3_MISS: { label: 'Three missed', shortLabel: 'MISS 3', group: 'Misses', requiresPlayer: true, requiresTeam: true, statDeltas: { fgAttempted: 1, threeAttempted: 1 }, flow: { suggestsEvents: ['REBOUND_OFF', 'REBOUND_DEF'], keepsPlayer: false } },
    REBOUND_OFF: { label: 'Offensive rebound', shortLabel: 'OREB', group: 'Possession', requiresPlayer: true, requiresTeam: true, statDeltas: { offRebounds: 1 } },
    REBOUND_DEF: { label: 'Defensive rebound', shortLabel: 'DREB', group: 'Possession', requiresPlayer: true, requiresTeam: true, statDeltas: { defRebounds: 1 }, flow: { flipsPossession: true } },
    ASSIST: { label: 'Assist', shortLabel: 'AST', group: 'Playmaking', requiresPlayer: true, requiresTeam: true, statDeltas: { assists: 1 } },
    STEAL: { label: 'Steal', shortLabel: 'STL', group: 'Defense', requiresPlayer: true, requiresTeam: true, statDeltas: { steals: 1 }, flow: { flipsPossession: true } },
    BLOCK: { label: 'Block', shortLabel: 'BLK', group: 'Defense', requiresPlayer: true, requiresTeam: true, statDeltas: { blocks: 1 } },
    TURNOVER: { label: 'Turnover', shortLabel: 'TO', group: 'Possession', requiresPlayer: true, requiresTeam: true, statDeltas: { turnovers: 1 }, flow: { flipsPossession: true } },
    FOUL: { label: 'Foul', shortLabel: 'FOUL', group: 'Discipline', requiresPlayer: true, requiresTeam: true, statDeltas: { fouls: 1 }, flow: { suggestsEvents: ['FT_MADE', 'FT_MISS'], flipsPossession: true, keepsPlayer: false } },
    SUBSTITUTION_IN: { label: 'Substitution in', requiresPlayer: true, requiresTeam: true, requiresSecondaryPlayer: true, confirmationMode: 'detail' },
    SUBSTITUTION_OUT: { label: 'Substitution out', requiresPlayer: true, requiresTeam: true },
  },
  playerStatFields: {
    points: { label: 'PTS', fullLabel: 'Points', type: 'integer', group: 'Scoring', aggregate: 'sum' },
    gamesPlayed: { label: 'GP', fullLabel: 'Games played', type: 'integer', group: 'Availability', aggregate: 'sum' },
    ppg: { label: 'PPG', fullLabel: 'Points per game', type: 'decimal', format: 'decimal1', group: 'Scoring', aggregate: 'average', derived: { type: 'perGame', stat: 'points' } },
    offRebounds: { label: 'OREB', fullLabel: 'Offensive rebounds', type: 'integer', group: 'Rebounding', aggregate: 'sum' },
    defRebounds: { label: 'DREB', fullLabel: 'Defensive rebounds', type: 'integer', group: 'Rebounding', aggregate: 'sum' },
    rebounds: { label: 'REB', fullLabel: 'Rebounds', type: 'integer', group: 'Rebounding', aggregate: 'sum', derived: { type: 'sum', stats: ['offRebounds', 'defRebounds'] } },
    rpg: { label: 'RPG', fullLabel: 'Rebounds per game', type: 'decimal', format: 'decimal1', group: 'Rebounding', aggregate: 'average', derived: { type: 'perGame', stat: 'rebounds' } },
    assists: { label: 'AST', fullLabel: 'Assists', type: 'integer', group: 'Playmaking', aggregate: 'sum' },
    apg: { label: 'APG', fullLabel: 'Assists per game', type: 'decimal', format: 'decimal1', group: 'Playmaking', aggregate: 'average', derived: { type: 'perGame', stat: 'assists' } },
    steals: { label: 'STL', type: 'integer', group: 'Defense', aggregate: 'sum' },
    blocks: { label: 'BLK', type: 'integer', group: 'Defense', aggregate: 'sum' },
    turnovers: { label: 'TO', type: 'integer', group: 'Possession', aggregate: 'sum' },
    fouls: { label: 'PF', type: 'integer', group: 'Discipline', aggregate: 'sum' },
    fgMade: { label: 'FGM', type: 'integer', aggregate: 'sum' },
    fgAttempted: { label: 'FGA', type: 'integer', aggregate: 'sum' },
    threeMade: { label: '3PM', type: 'integer', aggregate: 'sum' },
    threeAttempted: { label: '3PA', type: 'integer', aggregate: 'sum' },
    ftMade: { label: 'FTM', type: 'integer', aggregate: 'sum' },
    ftAttempted: { label: 'FTA', type: 'integer', aggregate: 'sum' },
  },
  teamStatFields: {
    wins: { label: 'W', type: 'integer', aggregate: 'sum' },
    losses: { label: 'L', type: 'integer', aggregate: 'sum' },
    pointsFor: { label: 'PF', type: 'integer', aggregate: 'sum' },
    pointsAgainst: { label: 'PA', type: 'integer', aggregate: 'sum' },
  },
  views: {
    profileHeadline: ['ppg', 'rpg', 'apg', 'gamesPlayed'],
    teamProfileHeadline: ['wins', 'losses', 'pointsFor', 'pointsAgainst'],
    boxScore: ['points', 'rebounds', 'assists', 'steals', 'blocks', 'turnovers'],
    leaderboard: ['points', 'rebounds', 'assists', 'fgMade'],
    livePad: [
      ['FT_MADE', 'FG2_MADE', 'FG3_MADE'],
      ['FT_MISS', 'FG2_MISS', 'FG3_MISS'],
      ['REBOUND_OFF', 'REBOUND_DEF', 'ASSIST'],
      ['STEAL', 'BLOCK', 'TURNOVER', 'FOUL'],
    ],
  },
  // NFHS-style thresholds (bonus at 7 team fouls, foul-out at 5 personal
  // fouls) — a single running-game bucket, not reset per half, since there's
  // no period tracking yet. Documented simplification, see DisciplineConfig.
  discipline: { foulEventTypes: ['FOUL'], bonusThreshold: 7, foulOutThreshold: 5 },
}
